version: "3.9"

networks:
  all:
    external: false

services:
  sample-admission:
    image: build.security/sample-admission
    container_name: sample-admission
    # volumes:
    #   - ./cert:/etc/cert
    command:
      - -cert
      - server.crt
      - -key
      - server.key
    restart: always
    ports:
      - "8000:8000"
    networks:
      - all